function escapeHtml(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
const cats=["calls","proposals","submittedLois","listings","acceptedLois","contracts"];
const catLabels={calls:"Calls",proposals:"Proposals",submittedLois:"Submitted LOI",listings:"Listings",acceptedLois:"Accepted LOI",contracts:"Contracts"};
function sum(rows,cat){return rows.reduce((t,r)=>t+Number(r.counts[cat]||0),0)}
function renderHomeStretchVerificationPage(data){
 const agents=data.teams.flatMap(t=>t.agents).sort((a,b)=>a.team.localeCompare(b.team)||a.displayName.localeCompare(b.displayName));
 const rows=agents.map(a=>`<tr><td>${escapeHtml(a.team)}</td><td>${escapeHtml(a.displayName)}</td>${cats.map(c=>`<td>${a.counts[c]}</td>`).join("")}<td>${a.rawPoints.toLocaleString("en-US")}</td><td>${a.handicap!==1?Math.round(a.handicap*100)+"%":"-"}</td><td>${a.handicappedPoints.toLocaleString("en-US")}</td><td>${a.netAdjustment}</td><td class="total">${a.totalPoints.toLocaleString("en-US")}</td></tr>`).join("");
 const totals=`<tr class="total"><td colspan="2">ALL AGENTS</td>${cats.map(c=>`<td>${sum(agents,c)}</td>`).join("")}<td colspan="4"></td><td>${agents.reduce((t,a)=>t+a.totalPoints,0).toLocaleString("en-US")}</td></tr>`;
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The Home Stretch Verification</title><style>
 *{box-sizing:border-box}body{margin:0;padding:26px;background:#0b1721;color:#f5f7fa;font-family:Arial,sans-serif}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:18px}h1{margin:0;font-size:34px}p{margin:6px 0 0;color:#9fb1bf}.actions a{color:#63c9e8;text-decoration:none;margin-left:18px}table{width:100%;border-collapse:separate;border-spacing:0;background:#132532;border:1px solid #2b4658;border-radius:12px;overflow:hidden;font-size:13px}th,td{padding:9px 10px;border-bottom:1px solid #294353;text-align:right}th{background:#1a3445;color:#b8c8d3;text-transform:uppercase;font-size:11px;letter-spacing:.4px;position:sticky;top:0}th:first-child,th:nth-child(2),td:first-child,td:nth-child(2){text-align:left}td.total,tr.total td{font-weight:800;background:#203d4c}tr.total td{border-bottom:0}tbody tr:hover td{background:#193343}</style></head><body>
 <header><div><h1>The Home Stretch Data Verification</h1><p>Raw record counts, ${escapeHtml(data.window.start)} through ${escapeHtml(data.window.dataThrough||"not started")}.</p></div><div class="actions"><a href="/home-stretch">Scoreboard</a><a href="/home-stretch/admin">Call Admin</a></div></header>
 <table><thead><tr><th>Squad</th><th>Agent</th>${cats.map(c=>`<th>${catLabels[c]}</th>`).join("")}<th>Raw Pts</th><th>Handicap</th><th>Handicapped Pts</th><th>Net Adj</th><th>Total</th></tr></thead><tbody>${rows}${totals}</tbody></table></body></html>`;
}
module.exports={renderHomeStretchVerificationPage};
