function escapeHtml(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
const cats=["calls","proposals","listings","lois","contracts"];
function sum(rows,bucket,cat){return rows.reduce((t,r)=>t+Number(r[bucket][cat]||0),0)}
function renderPipelineGrowthVerificationPage(data){
 const agents=data.teams.flatMap(t=>t.agents).sort((a,b)=>a.team.localeCompare(b.team)||a.displayName.localeCompare(b.displayName));
 const rows=agents.map(a=>`<tr><td>${escapeHtml(a.team)}</td><td>${escapeHtml(a.displayName)}</td>${cats.map(c=>`<td>${a.period1Full[c]}</td>`).join("")}${cats.map(c=>`<td>${a.period2[c]}</td>`).join("")}</tr>`).join("");
 const totals=`<tr class="total"><td colspan="2">ALL AGENTS</td>${cats.map(c=>`<td>${sum(agents,"period1Full",c)}</td>`).join("")}${cats.map(c=>`<td>${sum(agents,"period2",c)}</td>`).join("")}</tr>`;
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pipeline Growth Verification</title><style>
 *{box-sizing:border-box}body{margin:0;padding:26px;background:#0b1721;color:#f5f7fa;font-family:Arial,sans-serif}header{display:flex;justify-content:space-between;align-items:end;margin-bottom:18px}h1{margin:0;font-size:34px}p{margin:6px 0 0;color:#9fb1bf}.actions a{color:#63c9e8;text-decoration:none;margin-left:18px}table{width:100%;border-collapse:separate;border-spacing:0;background:#132532;border:1px solid #2b4658;border-radius:12px;overflow:hidden;font-size:13px}th,td{padding:9px 10px;border-bottom:1px solid #294353;text-align:right}th{background:#1a3445;color:#b8c8d3;text-transform:uppercase;font-size:11px;letter-spacing:.4px;position:sticky;top:0}th:first-child,th:nth-child(2),td:first-child,td:nth-child(2){text-align:left}th.group{font-size:13px;color:#fff;text-align:center;border-bottom:1px solid #436174}.p2{background:#183a43}.total td{font-weight:800;background:#203d4c;border-bottom:0}tr:last-child td{border-bottom:0}tbody tr:hover td{background:#193343}</style></head><body>
 <header><div><h1>Pipeline Growth Data Verification</h1><p>Raw record counts. Period 1 is the full Mar 30–May 15 window; Period 2 runs Jul 20 through ${escapeHtml(data.windows.period2Live.end||"not started")}.</p></div><div class="actions"><a href="/pipeline-growth-challenge">Scoreboard</a><a href="/pipeline-growth-challenge/admin">Call Admin</a></div></header>
 <table><thead><tr><th rowspan="2">Team</th><th rowspan="2">Agent</th><th colspan="5" class="group">Period 1 Full</th><th colspan="5" class="group p2">Period 2 Current</th></tr><tr>${cats.map(c=>`<th>${c}</th>`).join("")}${cats.map(c=>`<th class="p2">${c}</th>`).join("")}</tr></thead><tbody>${rows}${totals}</tbody></table></body></html>`;
}
module.exports={renderPipelineGrowthVerificationPage};
